logbook.strategy=without-body
logging.level.am.ik.mcp.yfinance.YfinanceServerApplication=debug
server.port=${PORT:8091}
spring.ai.mcp.server.name=yfinance-server
spring.ai.mcp.server.protocol=STREAMABLE
spring.application.name=yfinance-server
spring.threads.virtual.enabled=true
